In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization, LSTM, GRU
from sklearn.utils import resample
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
# Load the dataset
df = pd.read_csv('combodataset.csv', header = None)

df.columns = ['age', 'sex', 'cp', 'trestbps', 'chol',
              'fbs', 'restecg', 'thalach', 'exang', 
              'oldpeak', 'slope', 'target']

df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      40    1   2       140   289    0        0      172      0      0.0   
1      49    0   3       160   180    0        0      156      0      1.0   
2      37    1   2       130   283    0        1       98      0      0.0   
3      48    0   4       138   214    0        0      108      1      1.5   
4      54    1   3       150   195    0        0      122      0      0.0   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1185   45    1   1       110   264    0        0      132      0      1.2   
1186   68    1   4       144   193    1        0      141      0      3.4   
1187   57    1   4       130   131    0        0      115      1      1.2   
1188   57    0   2       130   236    0        2      174      0      0.0   
1189   38    1   3       138   175    0        0      173      0      0.0   

      slope  target  
0         1       0  
1         2       1  
2         1       0  
3         2       1  
4         1       0  
...     ...     ...  
1185      2       1  
1186      2       1  
1187      2       1  
1188      2       1  
1189      1       0  

[1190 rows x 12 columns]

In [3]:
# Separate features and target variable
X = df.drop('target', axis=1)
y = df['target']


In [4]:

# 1. Load and preprocess the data
# Assuming you have your data in the X and y variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [5]:
input_shape = (X_train.shape[1], 1)
input_shape_cnn = (X_train.shape[1], 1)

In [6]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [7]:
def build_cnn_model(input_shape):
    model = Sequential()
    model.add(Conv1D(filters=11, kernel_size=3, activation='relu', input_shape=input_shape))
    model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(0.25))
    model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [8]:
# Train the individual models
cnn_model = build_cnn_model(input_shape)
cnn_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
             callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
17/17 [==============================] - 2s 38ms/step - loss: 0.6433 - accuracy: 0.6603 - val_loss: 0.6271 - val_accuracy: 0.8151
Epoch 2/100
17/17 [==============================] - 0s 14ms/step - loss: 0.4908 - accuracy: 0.7839 - val_loss: 0.6123 - val_accuracy: 0.8291
Epoch 3/100
17/17 [==============================] - 0s 15ms/step - loss: 0.4648 - accuracy: 0.7995 - val_loss: 0.6082 - val_accuracy: 0.8179
Epoch 4/100
17/17 [==============================] - 0s 14ms/step - loss: 0.4750 - accuracy: 0.7983 - val_loss: 0.5918 - val_accuracy: 0.8011
Epoch 5/100
17/17 [==============================] - 0s 14ms/step - loss: 0.4361 - accuracy: 0.8163 - val_loss: 0.5844 - val_accuracy: 0.7367
Epoch 6/100
17/17 [==============================] - 0s 14ms/step - loss: 0.4407 - accuracy: 0.8031 - val_loss: 0.5761 - val_accuracy: 0.8347
Epoch 7/100
17/17 [==============================] - 0s 14ms/step - loss: 0.4177 - accuracy: 0.8283 - val_loss: 0.5677 - val_accuracy: 0.8319
Epoch 

In [9]:
# 8. Evaluate the model
test_loss, test_accuracy = cnn_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


12/12 [==============================] - 0s 3ms/step - loss: 0.3533 - accuracy: 0.8711
Test Loss: 0.3533
Test Accuracy: 0.8711


In [10]:
# Make predictions
y_pred = cnn_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


12/12 [==============================] - 0s 3ms/step
Confusion Matrix:
[[134  20]
 [ 26 177]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.87      0.85       154
           1       0.90      0.87      0.89       203

    accuracy                           0.87       357
   macro avg       0.87      0.87      0.87       357
weighted avg       0.87      0.87      0.87       357



In [17]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [18]:
def build_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(11, return_sequences=True, input_shape=input_shape))
    model.add(LSTM(32, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(64, return_sequences=True))
    model.add(LSTM(32))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [19]:
lstm_model = build_lstm_model(input_shape)
lstm_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
              callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
17/17 [==============================] - 14s 190ms/step - loss: 0.6252 - accuracy: 0.6771 - val_loss: 0.6535 - val_accuracy: 0.7395
Epoch 2/100
17/17 [==============================] - 1s 36ms/step - loss: 0.5832 - accuracy: 0.7059 - val_loss: 0.6645 - val_accuracy: 0.5798
Epoch 3/100
17/17 [==============================] - 1s 36ms/step - loss: 0.5658 - accuracy: 0.7059 - val_loss: 0.6662 - val_accuracy: 0.5910
Epoch 4/100
17/17 [==============================] - 1s 36ms/step - loss: 0.5550 - accuracy: 0.7215 - val_loss: 0.6667 - val_accuracy: 0.5882
Epoch 5/100
17/17 [==============================] - 1s 36ms/step - loss: 0.5652 - accuracy: 0.7203 - val_loss: 0.6676 - val_accuracy: 0.6050
Epoch 6/100
17/17 [==============================] - 1s 36ms/step - loss: 0.5493 - accuracy: 0.7287 - val_loss: 0.6618 - val_accuracy: 0.7171
Epoch 7/100
17/17 [==============================] - 1s 43ms/step - loss: 0.5322 - accuracy: 0.7299 - val_loss: 0.6341 - val_accuracy: 0.7423
Epoc

In [20]:
# 8. Evaluate the model
test_loss, test_accuracy = lstm_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


12/12 [==============================] - 0s 9ms/step - loss: 0.3317 - accuracy: 0.8796
Test Loss: 0.3317
Test Accuracy: 0.8796


In [21]:
# Make predictions
y_pred = lstm_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


12/12 [==============================] - 2s 9ms/step
Confusion Matrix:
[[131  23]
 [ 20 183]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       154
           1       0.89      0.90      0.89       203

    accuracy                           0.88       357
   macro avg       0.88      0.88      0.88       357
weighted avg       0.88      0.88      0.88       357



In [22]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [23]:
def build_gru_model(input_shape):
    model = Sequential()
    model.add(GRU(11, return_sequences=True, input_shape=input_shape))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(32, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(64, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(128, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(128))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(64, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [24]:
gru_model = build_gru_model(input_shape)
gru_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
             callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
17/17 [==============================] - 20s 256ms/step - loss: 0.6228 - accuracy: 0.6759 - val_loss: 0.6973 - val_accuracy: 0.4314
Epoch 2/100
17/17 [==============================] - 1s 69ms/step - loss: 0.5013 - accuracy: 0.7827 - val_loss: 0.7045 - val_accuracy: 0.4314
Epoch 3/100
17/17 [==============================] - 1s 69ms/step - loss: 0.4748 - accuracy: 0.7839 - val_loss: 0.7107 - val_accuracy: 0.4314
Epoch 4/100
17/17 [==============================] - 1s 69ms/step - loss: 0.4553 - accuracy: 0.7863 - val_loss: 0.7137 - val_accuracy: 0.4314
Epoch 5/100
17/17 [==============================] - 1s 69ms/step - loss: 0.4309 - accuracy: 0.8007 - val_loss: 0.7221 - val_accuracy: 0.4314
Epoch 6/100
17/17 [==============================] - 1s 70ms/step - loss: 0.4467 - accuracy: 0.8091 - val_loss: 0.7231 - val_accuracy: 0.4314
Epoch 7/100
17/17 [==============================] - 1s 69ms/step - loss: 0.4011 - accuracy: 0.8175 - val_loss: 0.7410 - val_accuracy: 0.4314
Epoc

In [25]:
# 8. Evaluate the model
test_loss, test_accuracy = gru_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


12/12 [==============================] - 0s 15ms/step - loss: 0.3369 - accuracy: 0.8908
Test Loss: 0.3369
Test Accuracy: 0.8908


In [26]:
# Make predictions
y_pred = gru_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


12/12 [==============================] - 3s 15ms/step
Confusion Matrix:
[[131  23]
 [ 16 187]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.85      0.87       154
           1       0.89      0.92      0.91       203

    accuracy                           0.89       357
   macro avg       0.89      0.89      0.89       357
weighted avg       0.89      0.89      0.89       357



In [30]:
# Make predictions using individual models
cnn_predictions = (cnn_model.predict(X_test) > 0.5).astype("int32")
lstm_predictions = (lstm_model.predict(X_test) > 0.5).astype("int32")
gru_predictions = (gru_model.predict(X_test) > 0.5).astype("int32")



12/12 [==============================] - 0s 15ms/step


In [31]:
# Combine predictions using a majority voting ensemble
ensemble_predictions = np.mean([cnn_predictions, lstm_predictions, gru_predictions], axis=0) >= 0.5
ensemble_predictions = ensemble_predictions.astype("int32")

In [32]:
# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.8964


In [33]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, ensemble_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, ensemble_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")


Confusion Matrix:
[[135  19]
 [ 18 185]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       154
           1       0.91      0.91      0.91       203

    accuracy                           0.90       357
   macro avg       0.89      0.89      0.89       357
weighted avg       0.90      0.90      0.90       357

Ensemble Accuracy: 0.8964


In [34]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.utils import resample
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from sklearn.model_selection import cross_val_score

In [35]:
# List of base models

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

svm_l_model = SVC(kernel="linear")
svm_l_model.fit(X_train, y_train)

svm_p_model = SVC(kernel="poly")
svm_p_model.fit(X_train, y_train)

svm_r_model = SVC(kernel="rbf")
svm_r_model.fit(X_train, y_train)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)

ab_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ab_model.fit(X_train, y_train)

xgb_model = XGBClassifier(n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

gpc_model = GaussianProcessClassifier(random_state=42)
gpc_model.fit(X_train, y_train)

GaussianProcessClassifier(random_state=42)

In [36]:
lr_predictions = lr_model.predict(X_test)
svm_l_predictions = svm_l_model.predict(X_test)
svm_p_predictions = svm_p_model.predict(X_test)
svm_r_predictions = svm_r_model.predict(X_test)
rf_predictions = rf_model.predict(X_test)
knn_predictions = knn_model.predict(X_test)
gb_predictions = gb_model.predict(X_test)
ab_predictions = ab_model.predict(X_test)
xgb_predictions = xgb_model.predict(X_test)
gpc_predictions = gpc_model.predict(X_test)


In [37]:
# Combine predictions using ensemble (Voting Classifier)
ensemble_predictions = np.column_stack((cnn_predictions, lstm_predictions, gru_predictions, lr_predictions, 
                                        svm_l_predictions, svm_p_predictions, svm_r_predictions, 
                                        rf_predictions, knn_predictions, gb_predictions, 
                                        ab_predictions, xgb_predictions, gpc_predictions))


In [38]:
# Perform majority voting to get the final prediction
final_predictions = np.mean(ensemble_predictions, axis=1) >= 0.5
final_predictions = final_predictions.astype("int32")

In [39]:
# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.9048


In [40]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, final_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, final_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Confusion Matrix:
[[134  20]
 [ 14 189]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       154
           1       0.90      0.93      0.92       203

    accuracy                           0.90       357
   macro avg       0.90      0.90      0.90       357
weighted avg       0.90      0.90      0.90       357

Ensemble Accuracy: 0.9048


In [41]:
# Combine predictions using ensemble (Voting Classifier)
ensemble_predictions = np.column_stack((cnn_predictions, lstm_predictions, gru_predictions, svm_r_predictions, 
                                        rf_predictions, knn_predictions, gb_predictions, 
                                        xgb_predictions, gpc_predictions))


In [42]:
# Perform majority voting to get the final prediction
final_predictions = np.mean(ensemble_predictions, axis=1) >= 0.5
final_predictions = final_predictions.astype("int32")

# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, final_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, final_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.9160
Confusion Matrix:
[[136  18]
 [ 12 191]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       154
           1       0.91      0.94      0.93       203

    accuracy                           0.92       357
   macro avg       0.92      0.91      0.91       357
weighted avg       0.92      0.92      0.92       357

Ensemble Accuracy: 0.9160
