In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization, LSTM, GRU
from sklearn.utils import resample
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
# Load the dataset
df = pd.read_csv('combodataset.csv', header = None)

df.columns = ['age', 'sex', 'cp', 'trestbps', 'chol',
              'fbs', 'restecg', 'thalach', 'exang', 
              'oldpeak', 'slope', 'target']

df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      40    1   2       140   289    0        0      172      0      0.0   
1      49    0   3       160   180    0        0      156      0      1.0   
2      37    1   2       130   283    0        1       98      0      0.0   
3      48    0   4       138   214    0        0      108      1      1.5   
4      54    1   3       150   195    0        0      122      0      0.0   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1185   45    1   1       110   264    0        0      132      0      1.2   
1186   68    1   4       144   193    1        0      141      0      3.4   
1187   57    1   4       130   131    0        0      115      1      1.2   
1188   57    0   2       130   236    0        2      174      0      0.0   
1189   38    1   3       138   175    0        0      173      0      0.0   

      slope  target  
0         1       0  
1         2       1  
2         1       0  
3         2       1  
4         1       0  
...     ...     ...  
1185      2       1  
1186      2       1  
1187      2       1  
1188      2       1  
1189      1       0  

[1190 rows x 12 columns]

In [3]:
# Separate features and target variable
X = df.drop('target', axis=1)
y = df['target']


In [4]:

# 1. Load and preprocess the data
# Assuming you have your data in the X and y variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [5]:
input_shape = (X_train.shape[1], 1)
input_shape_cnn = (X_train.shape[1], 1)

In [10]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [11]:
def build_cnn_model(input_shape):
    model = Sequential()
    model.add(Conv1D(filters=11, kernel_size=3, activation='relu', input_shape=input_shape))
    model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(0.25))
    model.add(Conv1D(filters=128, kernel_size=3, activation='relu'))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [12]:
# Train the individual models
cnn_model = build_cnn_model(input_shape)
cnn_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
             callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
15/15 [==============================] - 2s 37ms/step - loss: 0.6085 - accuracy: 0.6499 - val_loss: 0.6263 - val_accuracy: 0.7563
Epoch 2/100
15/15 [==============================] - 0s 16ms/step - loss: 0.5188 - accuracy: 0.7633 - val_loss: 0.6078 - val_accuracy: 0.7542
Epoch 3/100
15/15 [==============================] - 0s 15ms/step - loss: 0.4940 - accuracy: 0.7829 - val_loss: 0.5928 - val_accuracy: 0.7143
Epoch 4/100
15/15 [==============================] - 0s 10ms/step - loss: 0.4701 - accuracy: 0.7941 - val_loss: 0.5989 - val_accuracy: 0.6282
Epoch 5/100
15/15 [==============================] - 0s 16ms/step - loss: 0.4523 - accuracy: 0.7997 - val_loss: 0.5838 - val_accuracy: 0.7458
Epoch 6/100
15/15 [==============================] - 0s 15ms/step - loss: 0.4392 - accuracy: 0.7983 - val_loss: 0.5705 - val_accuracy: 0.7710
Epoch 7/100
15/15 [==============================] - 0s 15ms/step - loss: 0.4585 - accuracy: 0.7969 - val_loss: 0.5660 - val_accuracy: 0.7017
Epoch 

In [13]:
# 8. Evaluate the model
test_loss, test_accuracy = cnn_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


15/15 [==============================] - 0s 3ms/step - loss: 0.3425 - accuracy: 0.8676
Test Loss: 0.3425
Test Accuracy: 0.8676


In [14]:
# Make predictions
y_pred = cnn_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


15/15 [==============================] - 0s 2ms/step
Confusion Matrix:
[[182  36]
 [ 27 231]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.83      0.85       218
           1       0.87      0.90      0.88       258

    accuracy                           0.87       476
   macro avg       0.87      0.87      0.87       476
weighted avg       0.87      0.87      0.87       476



In [19]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [20]:
def build_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(11, return_sequences=True, input_shape=input_shape))
    model.add(LSTM(32, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))
    model.add(LSTM(64, return_sequences=True))
    model.add(LSTM(32))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [23]:
lstm_model = build_lstm_model(input_shape)
lstm_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
              callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
15/15 [==============================] - 13s 203ms/step - loss: 0.6445 - accuracy: 0.6527 - val_loss: 0.6749 - val_accuracy: 0.5294
Epoch 2/100
15/15 [==============================] - 1s 40ms/step - loss: 0.5968 - accuracy: 0.7003 - val_loss: 0.6642 - val_accuracy: 0.5567
Epoch 3/100
15/15 [==============================] - 1s 50ms/step - loss: 0.5723 - accuracy: 0.7031 - val_loss: 0.6487 - val_accuracy: 0.6218
Epoch 4/100
15/15 [==============================] - 1s 39ms/step - loss: 0.5866 - accuracy: 0.7115 - val_loss: 0.6567 - val_accuracy: 0.6471
Epoch 5/100
15/15 [==============================] - 1s 39ms/step - loss: 0.5529 - accuracy: 0.7325 - val_loss: 0.6584 - val_accuracy: 0.6239
Epoch 6/100
15/15 [==============================] - 1s 39ms/step - loss: 0.5477 - accuracy: 0.7339 - val_loss: 0.6548 - val_accuracy: 0.6155
Epoch 7/100
15/15 [==============================] - 1s 39ms/step - loss: 0.5455 - accuracy: 0.7353 - val_loss: 0.6517 - val_accuracy: 0.6345
Epoc

In [24]:
# 8. Evaluate the model
test_loss, test_accuracy = lstm_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


15/15 [==============================] - 0s 10ms/step - loss: 0.3274 - accuracy: 0.8824
Test Loss: 0.3274
Test Accuracy: 0.8824


In [25]:
# Make predictions
y_pred = lstm_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


15/15 [==============================] - 3s 10ms/step
Confusion Matrix:
[[187  31]
 [ 25 233]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.86      0.87       218
           1       0.88      0.90      0.89       258

    accuracy                           0.88       476
   macro avg       0.88      0.88      0.88       476
weighted avg       0.88      0.88      0.88       476



In [26]:
# 4. Hyperparameter tuning
learning_rate = 0.001
batch_size = 50
epochs = 100



# 5. Learning rate scheduling
lr_scheduler = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=learning_rate, decay_steps=10000, decay_rate=0.9
)
optimizer = keras.optimizers.Adam(learning_rate=lr_scheduler)



# 6. Regularization techniques
callback_early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True
)
callback_checkpoint = keras.callbacks.ModelCheckpoint(
    'model_checkpoint.h5', save_best_only=True
)



In [27]:
def build_gru_model(input_shape):
    model = Sequential()
    model.add(GRU(11, return_sequences=True, input_shape=input_shape))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(32, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(64, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(128, return_sequences=True))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(GRU(128))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(64, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.1))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))  # Output layer
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model


In [28]:
gru_model = build_gru_model(input_shape)
gru_model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test),
             callbacks=[callback_early_stopping, callback_checkpoint])


Epoch 1/100
15/15 [==============================] - 19s 284ms/step - loss: 0.6109 - accuracy: 0.6765 - val_loss: 0.6882 - val_accuracy: 0.5882
Epoch 2/100
15/15 [==============================] - 1s 74ms/step - loss: 0.5187 - accuracy: 0.7605 - val_loss: 0.6883 - val_accuracy: 0.6975
Epoch 3/100
15/15 [==============================] - 1s 89ms/step - loss: 0.4730 - accuracy: 0.7675 - val_loss: 0.6874 - val_accuracy: 0.5588
Epoch 4/100
15/15 [==============================] - 1s 93ms/step - loss: 0.4571 - accuracy: 0.7927 - val_loss: 0.6844 - val_accuracy: 0.6071
Epoch 5/100
15/15 [==============================] - 1s 86ms/step - loss: 0.4685 - accuracy: 0.7801 - val_loss: 0.6818 - val_accuracy: 0.5105
Epoch 6/100
15/15 [==============================] - 1s 86ms/step - loss: 0.4418 - accuracy: 0.8067 - val_loss: 0.6774 - val_accuracy: 0.5126
Epoch 7/100
15/15 [==============================] - 1s 73ms/step - loss: 0.4143 - accuracy: 0.8165 - val_loss: 0.6807 - val_accuracy: 0.4643
Epoc

In [29]:
# 8. Evaluate the model
test_loss, test_accuracy = gru_model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss:.4f}')
print(f'Test Accuracy: {test_accuracy:.4f}')


15/15 [==============================] - 0s 17ms/step - loss: 0.3260 - accuracy: 0.9034
Test Loss: 0.3260
Test Accuracy: 0.9034


In [30]:
# Make predictions
y_pred = gru_model.predict(X_test)
y_pred_classes = np.round(y_pred)


# Calculate confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report


conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


15/15 [==============================] - 3s 16ms/step
Confusion Matrix:
[[191  27]
 [ 19 239]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.88      0.89       218
           1       0.90      0.93      0.91       258

    accuracy                           0.90       476
   macro avg       0.90      0.90      0.90       476
weighted avg       0.90      0.90      0.90       476



In [35]:
# Make predictions using individual models
cnn_predictions = (cnn_model.predict(X_test) > 0.5).astype("int32")
lstm_predictions = (lstm_model.predict(X_test) > 0.5).astype("int32")
gru_predictions = (gru_model.predict(X_test) > 0.5).astype("int32")



15/15 [==============================] - 0s 15ms/step


In [36]:
# Combine predictions using a majority voting ensemble
ensemble_predictions = np.mean([cnn_predictions, lstm_predictions, gru_predictions], axis=0) >= 0.5
ensemble_predictions = ensemble_predictions.astype("int32")

In [37]:
# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.9055


In [39]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, ensemble_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, ensemble_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")


Confusion Matrix:
[[193  25]
 [ 20 238]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.89      0.90       218
           1       0.90      0.92      0.91       258

    accuracy                           0.91       476
   macro avg       0.91      0.90      0.90       476
weighted avg       0.91      0.91      0.91       476

Ensemble Accuracy: 0.9055


In [40]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.utils import resample
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from sklearn.model_selection import cross_val_score

In [41]:
# List of base models

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

svm_l_model = SVC(kernel="linear")
svm_l_model.fit(X_train, y_train)

svm_p_model = SVC(kernel="poly")
svm_p_model.fit(X_train, y_train)

svm_r_model = SVC(kernel="rbf")
svm_r_model.fit(X_train, y_train)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)

ab_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ab_model.fit(X_train, y_train)

xgb_model = XGBClassifier(n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

gpc_model = GaussianProcessClassifier(random_state=42)
gpc_model.fit(X_train, y_train)

GaussianProcessClassifier(random_state=42)

In [42]:
lr_predictions = lr_model.predict(X_test)
svm_l_predictions = svm_l_model.predict(X_test)
svm_p_predictions = svm_p_model.predict(X_test)
svm_r_predictions = svm_r_model.predict(X_test)
rf_predictions = rf_model.predict(X_test)
knn_predictions = knn_model.predict(X_test)
gb_predictions = gb_model.predict(X_test)
ab_predictions = ab_model.predict(X_test)
xgb_predictions = xgb_model.predict(X_test)
gpc_predictions = gpc_model.predict(X_test)


In [43]:
# Combine predictions using ensemble (Voting Classifier)
ensemble_predictions = np.column_stack((cnn_predictions, lstm_predictions, gru_predictions, lr_predictions, 
                                        svm_l_predictions, svm_p_predictions, svm_r_predictions, 
                                        rf_predictions, knn_predictions, gb_predictions, 
                                        ab_predictions, xgb_predictions, gpc_predictions))


In [44]:
# Perform majority voting to get the final prediction
final_predictions = np.mean(ensemble_predictions, axis=1) >= 0.5
final_predictions = final_predictions.astype("int32")

In [45]:
# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.9181


In [46]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, final_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, final_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Confusion Matrix:
[[193  25]
 [ 14 244]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       218
           1       0.91      0.95      0.93       258

    accuracy                           0.92       476
   macro avg       0.92      0.92      0.92       476
weighted avg       0.92      0.92      0.92       476

Ensemble Accuracy: 0.9181


In [47]:
# Combine predictions using ensemble (Voting Classifier)
ensemble_predictions = np.column_stack((cnn_predictions, lstm_predictions, gru_predictions, svm_r_predictions, 
                                        rf_predictions, knn_predictions, gb_predictions, 
                                        xgb_predictions, gpc_predictions))


In [48]:
# Perform majority voting to get the final prediction
final_predictions = np.mean(ensemble_predictions, axis=1) >= 0.5
final_predictions = final_predictions.astype("int32")

# Calculate accuracy of the ensemble
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, final_predictions)

print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, final_predictions)
print("Classification Report:")
print(class_report)

# Evaluate ensemble accuracy
ensemble_accuracy = accuracy_score(y_test, final_predictions)
print(f"Ensemble Accuracy: {ensemble_accuracy:.4f}")

Ensemble Accuracy: 0.9223
Confusion Matrix:
[[195  23]
 [ 14 244]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       218
           1       0.91      0.95      0.93       258

    accuracy                           0.92       476
   macro avg       0.92      0.92      0.92       476
weighted avg       0.92      0.92      0.92       476

Ensemble Accuracy: 0.9223
